In [2]:
from process_data import * # import all functions from process_data.py
from A1.a1 import A1
from A2.a2 import A2
# PATH TO ALL IMAGES


basedir = os.path.abspath('')
dataset_dir = os.path.join(basedir,'Datasets')
celeba_images_dir = os.path.join(dataset_dir,'celeba', 'img')
celeba_test_images_dir = os.path.join(dataset_dir,'celeba_test', 'img')
cartoon_images_dir = os.path.join(dataset_dir,'cartoon_set', 'img')
cartoon_test_images_dir = os.path.join(dataset_dir,'cartoon_set_test', 'img')
celeba_labels_dir = os.path.join(dataset_dir,'celeba', 'labels.csv')
celeba_test_labels_dir = os.path.join(dataset_dir,'celeba_test', 'labels.csv')
cartoon_labels_dir = os.path.join(dataset_dir,'cartoon_set', 'labels.csv')
cartoon_test_labels_dir = os.path.join(dataset_dir,'cartoon_set_test', 'labels.csv')

run_a1 = True
run_a2 = True
run_b1 = True
run_b2 = True


In [3]:
if run_a1 or run_a2:
    train_celeb_images = load_images(images_dir=celeba_images_dir,file_type='jpg', num_imgs=5000) # load images
    test_celeb_images = load_images(images_dir=celeba_test_images_dir,file_type='jpg', num_imgs=1000) # load images

    train_gender_celeb_labels = load_labels(label_dir=celeba_labels_dir, label_col_name='gender')
    test_gender_celeb_labels = load_labels(label_dir=celeba_test_labels_dir, label_col_name='gender')

    train_smiling_celeb_labels = load_labels(label_dir=celeba_labels_dir, label_col_name='smiling')
    test_smiling_celeb_labels = load_labels(label_dir=celeba_test_labels_dir, label_col_name='smiling')

    train_celeb_features, train_gender_labels, train_smiling_labels = extract_features_labels(train_celeb_images, train_gender_celeb_labels, train_smiling_celeb_labels) # extract features and labels
    test_celeb_features, test_gender_labels, test_smiling_labels = extract_features_labels(test_celeb_images, test_gender_celeb_labels, test_smiling_celeb_labels) # extract features and labels


In [4]:

if run_b1 or run_b2:
    train_cartoon_images = load_images(images_dir=cartoon_images_dir,file_type='png', num_imgs=10000) # load images
    test_cartoon_images = load_images(images_dir=cartoon_test_images_dir,file_type='png', num_imgs=2500) # load images

    train_eye_color_cartoon_labels = load_labels(label_dir=cartoon_labels_dir, label_col_name='eye_color')
    test_eye_color_cartoon_labels = load_labels(label_dir=cartoon_test_labels_dir, label_col_name='eye_color')

    train_face_shape_cartoon_labels = load_labels(label_dir=cartoon_labels_dir, label_col_name='face_shape')
    test_face_shape_cartoon_labels = load_labels(label_dir=cartoon_test_labels_dir, label_col_name='face_shape')

    train_cartoon_features, train_eye_color_labels, train_face_shape_labels = extract_features_labels(train_cartoon_images, train_eye_color_cartoon_labels, train_face_shape_cartoon_labels) # extract features and labels
    test_cartoon_features, test_eye_color_labels, test_face_shape_labels = extract_features_labels(test_cartoon_images, test_eye_color_cartoon_labels, test_face_shape_cartoon_labels) # extract features and labels

KeyboardInterrupt: 

In [13]:
print(train_celeb_images[0])
x = np.reshape(train_celeb_images,(5000,218*178))


[[222 222 222 ... 226 234 235]
 [222 222 222 ... 228 234 235]
 [222 222 222 ... 230 235 236]
 ...
 [ 67  42  72 ...  54  55  55]
 [ 55  63  92 ...  48  50  50]
 [ 93 129 171 ...  48  50  50]]


In [14]:
print(x[0])

[222 222 222 ...  48  50  50]


In [15]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
SVC_classifier = SVC(kernel='linear')
SVC_classifier.fit(np.reshape(train_celeb_images,(5000,218*178)),train_gender_celeb_labels)
SVC_predictions = SVC_classifier.predict(np.reshape(test_celeb_images,(1000,218*178)))
score = accuracy_score(SVC_predictions,test_gender_celeb_labels)
print(score)

ValueError: Found array with dim 3. SVC expected <= 2.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
LR_classifier = LogisticRegression()
LR_classifier.fit(np.reshape(train_celeb_images,(5000,218*178)),train_gender_celeb_labels)
LR_predictions = LR_classifier.predict(np.reshape(test_celeb_images,(1000,218*178)))
score = accuracy_score(LR_predictions,test_gender_celeb_labels)
print(score)